import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer, treasury, user] = await ethers.getSigners();

  console.log("=".repeat(60));
  console.log("Local Development Setup");
  console.log("=".repeat(60));
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Treasury: ${treasury.address}`);
  console.log(`Test User: ${user.address}`);
  console.log("=".repeat(60));

  const JPYC_DECIMALS = 18;
  const MIN_SAISEN = ethers.parseUnits("115", JPYC_DECIMALS);

  // 1. Deploy MockERC20 (JPYC)
  console.log("\n[1/5] Deploying MockERC20 (JPYC)...");
  const MockERC20Factory = await ethers.getContractFactory("MockERC20");
  const jpyc = await MockERC20Factory.deploy("JPY Coin", "JPYC", JPYC_DECIMALS);
  await jpyc.waitForDeployment();
  const jpycAddress = await jpyc.getAddress();
  console.log(`  MockERC20 (JPYC) deployed to: ${jpycAddress}`);

  // 2. Deploy OfferingsNFT1155
  console.log("\n[2/5] Deploying OfferingsNFT1155...");
  const NFTFactory = await ethers.getContractFactory("OfferingsNFT1155");
  const nft = await NFTFactory.deploy("http://localhost:3000/metadata/{id}.json");
  await nft.waitForDeployment();
  const nftAddress = await nft.getAddress();
  console.log(`  OfferingsNFT1155 deployed to: ${nftAddress}`);

  // 3. Deploy SaisenRouter
  console.log("\n[3/5] Deploying SaisenRouter...");
  const RouterFactory = await ethers.getContractFactory("SaisenRouter");
  const router = await RouterFactory.deploy(
    jpycAddress,
    nftAddress,
    treasury.address,
    MIN_SAISEN
  );
  await router.waitForDeployment();
  const routerAddress = await router.getAddress();
  console.log(`  SaisenRouter deployed to: ${routerAddress}`);

  // 4. Grant MINTER_ROLE to Router
  console.log("\n[4/5] Granting MINTER_ROLE to Router...");
  const MINTER_ROLE = await nft.MINTER_ROLE();
  await nft.grantRole(MINTER_ROLE, routerAddress);
  console.log(`  MINTER_ROLE granted to Router`);

  // 5. Mint test JPYC to first 5 accounts
  console.log("\n[5/5] Minting test JPYC...");
  const signers = await ethers.getSigners();
  const mintAmount = ethers.parseUnits("10000", JPYC_DECIMALS); // 10,000 JPYC
  for (let i = 0; i < Math.min(5, signers.length); i++) {
    await jpyc.mint(signers[i].address, mintAmount);
    console.log(`  Minted 10,000 JPYC to ${signers[i].address}`);
  }

  // Update frontend .env.local
  const frontendEnvPath = path.join(__dirname, "..", "frontend", ".env.local");
  const envContent = `# Generated by local-setup.ts - ${new Date().toISOString()}
VITE_JPYC_ADDRESS_AMOY=${jpycAddress}
VITE_ROUTER_ADDRESS_AMOY=${routerAddress}
VITE_NFT_ADDRESS_AMOY=${nftAddress}
`;

  fs.writeFileSync(frontendEnvPath, envContent);
  console.log(`\nUpdated frontend/.env.local with contract addresses`);

  // Summary
  console.log("\n" + "=".repeat(60));
  console.log("Local Setup Complete!");
  console.log("=".repeat(60));
  console.log("\nContract Addresses (Hardhat Local):");
  console.log(`  JPYC:    ${jpycAddress}`);
  console.log(`  NFT:     ${nftAddress}`);
  console.log(`  Router:  ${routerAddress}`);
  console.log(`  Treasury: ${treasury.address}`);
  console.log("\nTest Accounts with 10,000 JPYC:");
  for (let i = 0; i < Math.min(5, signers.length); i++) {
    console.log(`  [${i}] ${signers[i].address}`);
  }
  console.log("\n" + "=".repeat(60));
  console.log("Next Steps:");
  console.log("  1. Keep this terminal running (Hardhat node)");
  console.log("  2. In another terminal: cd frontend && npm run dev");
  console.log("  3. Connect MetaMask to http://127.0.0.1:8545 (Chain ID: 31337)");
  console.log("  4. Import a test account using private key from Hardhat");
  console.log("=".repeat(60));
}

main()
  .then(() => {
    // Don't exit - keep node running if this is run with --network localhost
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
